### ISSUE TITLE
ability to remove a remote repo

### ISSUE THREAD

**Issue by agonbina** [maximilianschmitt/gitclick#8]
Add the ability to remove a repository, similar to `create`, ex: `gitclick remove [<repository>] [from <organization>] [on <account>]`

**Comment by maximilianschmitt** [comment]
Yes, a `remove` command would definitely be helpful. I'm a little concerned about the wording. We could just use the wording from the `create` command, so that would be:

```
gitclick remove <repo> as <organization> on <account>
```

Or – a more natural language might be:

```
gitclick remove <repo> as <organization> from <account>
```

Maybe we could just alias `from` as `on` and then you wouldn't have to think about it.

**Comment by agonbina** [comment]
yeah either way works as long as its there and i don't have to manually delete a repo on Bitbucket :)
